### ISSUE TITLE
Gradle plugin "docker.run" & "docker.minecraft_servers" not found in Gradle

### ISSUE THREAD

**Issue by KleinDevDE** [WolfyScript/dev-tools#1]
Hi  
  
Unfortunately I am not able to implement one of the two Gradle plugins in my Gradle Config.  
The respective plugins cannot be found.  
  
Adding your repository “https://maven.wolfyscript.com/repositories” does not work either.  
Only 404 responses according to your gradle build, seems like a password is required for this repo (see the gradle build in this repo).  

Is the Gradle plugin intended for the public?  

**build.gradle**
```
plugins {
    id 'java'
    id 'com.wolfyscript.devtools.docker.minecraft_servers' version '2.0-SNAPSHOT'
}
```

**com.wolfyscript.devtools.docker.run**
```
* What went wrong:
Plugin [id: 'com.wolfyscript.devtools.docker.run', version: '2.0-SNAPSHOT'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Included Builds (No included builds contain this plugin)
- Plugin Repositories (could not resolve plugin artifact 'com.wolfyscript.devtools.docker.run:com.wolfyscript.devtools.docker.run.gradle.plugin:2.0-SNAPSHOT')
  Searched in the following repositories:
    Gradle Central Plugin Repository

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

CONFIGURE FAILED in 419ms
```

**com.wolfyscript.devtools.docker.minecraft_servers**
```
* What went wrong:
Plugin [id: 'com.wolfyscript.devtools.docker.minecraft_servers', version: '2.0-SNAPSHOT'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Included Builds (No included builds contain this plugin)
- Plugin Repositories (could not resolve plugin artifact 'com.wolfyscript.devtools.docker.minecraft_servers:com.wolfyscript.devtools.docker.minecraft_servers.gradle.plugin:2.0-SNAPSHOT')
  Searched in the following repositories:
    Gradle Central Plugin Repository

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

CONFIGURE FAILED in 354ms
```

**Comment by WolfyScript** [comment]
yeah I've changed the repo from nexus to artifactory and it got another sub domain.
`artifacts.wolfyscript.com`
But it isn't publiahed yet. I first need to update this repo to use the artifactory publish plugin.

**Comment by WolfyScript** [comment]
It is published to the repository and should be available now.

The plugins are published to a private repository that you need to add to the plugin repositories.
> **settings.gradle.kts** 
> ```kotlin
> pluginManagement {
>     repositories {
>         maven("https://artifacts.wolfyscript.com/artifactory/gradle-dev")
>         // ... (other repos)
>     }
> }
> ```

I had to reconfigure the permissions in artifactory to give permission to the repo, so if there are any issue with connecting to to the repo let me know.
